

                               term  ::=  argument argument argument     (1)

                                       |  argument<NO_WHITESPACE>"⁻¹"    (2)

                                       ;

