

                               term  ::=  argument argument argument 

                                       |  argument<NO_WHITESPACE>"⁻¹"

                                       |  operation

                                       ;


                          operation  ::=  "◯" ;

